version: '3.8'
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      ACCEPT_EULA: Y
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    